apiVersion: v2
name: uptime-monitor
description: Uptime Monitor API, checker CronJob and PostgreSQL
type: application
version: 0.1.0        # version of the chart itself
appVersion: "dev"     # version of the app it deploys