{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: api
  endpoints:
    - port: http       
      path: /metrics      
      interval: 15s
{{- end }}